#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-/tmp/sp-demo}"
REPO="$ROOT/repo"
WORKTREES="$ROOT/worktrees"

case "$ROOT" in
  ""|"/")
    echo "Refusing to use '$ROOT' as a demo root" >&2
    exit 1
    ;;
esac

rm -rf "$ROOT"
mkdir -p "$REPO" "$WORKTREES"

git -C "$REPO" init
git -C "$REPO" checkout -b main
git -C "$REPO" config user.name "sp demo"
git -C "$REPO" config user.email "demo@example.com"

cat > "$REPO/README.md" <<'EOF'
# sp demo

This repository was generated by scripts/demo-repo.sh.
EOF

git -C "$REPO" add README.md
git -C "$REPO" -c commit.gpgsign=false commit -m "Initial demo app"

git -C "$REPO" worktree add -b agent/A "$WORKTREES/agent-A" main
printf "agent A\n" > "$WORKTREES/agent-A/agent-a.txt"
git -C "$WORKTREES/agent-A" add agent-a.txt
git -C "$WORKTREES/agent-A" -c commit.gpgsign=false commit -m "Add agent A change"

git -C "$REPO" worktree add -b agent/B "$WORKTREES/agent-B" main
printf "dirty\n" > "$WORKTREES/agent-B/dirty.txt"

cat > "$REPO/sp.toml" <<EOF
base_branch = "main"
deploy_command = "echo deploy demo"

[[worktree]]
label = "agent-A"
branch = "agent/A"
path = "$WORKTREES/agent-A"

[[worktree]]
label = "agent-B"
branch = "agent/B"
path = "$WORKTREES/agent-B"
EOF

git -C "$REPO" add sp.toml
git -C "$REPO" -c commit.gpgsign=false commit -m "Configure sp demo"

echo "Created demo repo at $REPO"
echo "Run:"
echo "  cd $REPO"
echo "  sp"
